-- 🚀 MASSIVE SILENT MONEY CONTENT EXPANSION
-- This script adds 12 high-quality business/income ideas for EACH of the 9 classifications.
-- Total: 108 new vetted opportunities for the Indian landscape.

DO $$
DECLARE
    cat_investments UUID := (SELECT id FROM categories WHERE slug = 'investments');
    cat_content     UUID := (SELECT id FROM categories WHERE slug = 'content-creation');
    cat_affiliate   UUID := (SELECT id FROM categories WHERE slug = 'affiliate-marketing');
    cat_digital     UUID := (SELECT id FROM categories WHERE slug = 'digital-products');
    cat_rental      UUID := (SELECT id FROM categories WHERE slug = 'rental-income');
    cat_online      UUID := (SELECT id FROM categories WHERE slug = 'online-business');
    cat_freelance   UUID := (SELECT id FROM categories WHERE slug = 'freelancing');
    cat_automation  UUID := (SELECT id FROM categories WHERE slug = 'automation');
    cat_offline     UUID := (SELECT id FROM categories WHERE slug = 'offline-business');
BEGIN

-- 1. INVESTMENTS (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('P2P Lending (12% Club)', 'p2p-lending-india', cat_investments, 'Lend money to verified borrowers via NBFC-P2P platforms.', 'Invest your idle cash in P2P lending platforms like 12% Club or LenDenClub. These platforms lend your money to individual borrowers or small businesses.', 10000, 1000, 'passive', 'high', 'Unlike FDs, capital is not guaranteed. Borrowers can default. Stick to regulated platforms.', true),
('Index Fund SIP', 'index-fund-sip', cat_investments, 'Automated investing in the top 50 companies of India.', 'Start a Systematic Investment Plan in a Nifty 50 or Sensex Index Fund. Low cost, high diversification, and long-term wealth creation.', 500, 0, 'passive', 'medium', 'Market volatility is real. Requires a 5-10 year horizon to see significant compounding.', true),
('Sovereign Gold Bonds', 'sgb-investing', cat_investments, 'Government of India backed gold bonds with 2.5% annual interest.', 'Buy SGBs during issuance or from secondary markets. You get the benefit of gold price appreciation PLUS a fixed interest.', 5000, 100, 'passive', 'low', '8-year lock-in period (though tradable on exchanges). No physical gold storage risk.', false),
('Corporate Fixed Deposits', 'corporate-fd-india', cat_investments, 'Higher interest rates than banks by lending to top companies.', 'Invest in FDs of companies like HDFC, Bajaj Finance, or Mahindra Finance. They offer 1-2% more interest than traditional banks.', 25000, 200, 'passive', 'medium', 'Only choose AAA or AA+ rated companies to minimize default risk.', false),
('Smallcase Portfolio', 'smallcase-thematic-investing', cat_investments, 'Curated baskets of stocks based on themes like EV or Rural growth.', 'Invest in "smallcases" - curated stock baskets managed by SEBI-registered experts. Easy way to bet on specific Indian growth sectors.', 5000, 0, 'passive', 'high', 'Requires active tracking of themes. Portfolio rebalancing fees apply.', false),
('Senior Citizen Savings Scheme', 'scss-investment', cat_investments, 'Safe 8%+ interest for retirees (invest for parents).', 'A government-backed scheme for those above 60. Highest safety and quarterly payouts.', 1000, 600, 'passive', 'low', 'Only for senior citizens. Maximum limit of 30 lakhs per person.', false),
('Grip Invest: Fractional Lease', 'grip-invest-leasing', cat_investments, 'Lease equipment to startups and earn monthly rentals.', 'Invest in fractional asset leasing. You own a part of a fleet or equipment leased to companies like Uber or BigBasket.', 20000, 1500, 'passive', 'high', 'Counter-party risk. If the startup fails, your income stops. Not liquid.', true),
('High-Yield Neo-Banks', 'neobank-savings', cat_investments, 'Earn 7% interest on savings accounts with new-age banks.', 'Banks like Equitas or IDFC offer significantly higher interest on savings accounts compared to big banks.', 5000, 50, 'passive', 'low', 'Safety is ensured up to 5 lakhs by DICGC. Higher rates may decrease as the bank grows.', false),
('Mutual Fund SWP', 'mf-swp-passive', cat_investments, 'Generate "monthly salary" from your existing MF units.', 'Systematic Withdrawal Plan allows you to withdraw a fixed amount monthly while keeping the rest invested.', 100000, 2000, 'passive', 'medium', 'If market drops significantly, you might eat into your principal faster.', false),
('Venture Debt', 'venture-debt-investing', cat_investments, 'High entry-point debt investing in late-stage startups.', 'Lend to profitable startups via managed debt funds. Targeting 14-16% IRR.', 100000, 5000, 'passive', 'high', 'Illiquid entry. Only for high-net-worth investors looking for diversification.', false),
('Invoice Discounting (KredX)', 'invoice-discounting-india', cat_investments, 'Fund unpaid invoices of blue-chip companies for short-term gains.', 'Discounting invoices of companies like Amazon/Reliance. Short cycle (30-90 days).', 50000, 1000, 'passive', 'high', 'Risk is tied to the paying company''s creditworthiness.', false),
('Pre-IPO / Secondary Shares', 'pre-ipo-investing', cat_investments, 'Buy shares of companies before they list on NSE/BSE.', 'Platforms like Altius or Stockify let you buy unlisted shares of Swiggy, Oyo, etc.', 50000, 0, 'passive', 'high', 'Very high risk. Capital can stay locked for years if the IPO is delayed.', false);

-- 2. CONTENT CREATION (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('LinkedIn Ghostwriting', 'linkedin-ghostwriting-service', cat_content, 'Write posts for busy CEOs and Founders to build their brand.', 'Manage personal branding for executives. Charge per post or monthly retainer.', 0, 15000, 'active', 'low', 'Requires high understanding of industry trends and a "voice" match.', true),
('Technical Blogging (Hashnode)', 'technical-blogging-dev', cat_content, 'Write about code/tech and earn via ads and sponsors.', 'Focus on niche tech like Rust, AI, or Web3. Build an audience of developers.', 0, 5000, 'active', 'medium', 'Takes 6 months to see traffic from Google/Social.', false),
('Educational Podcasting', 'podcasting-education-india', cat_content, 'Teach a skill via audio on Spotify and YouTube.', 'Focus on regional languages. Niche: Agri-tech, UPSC tips, or Personal Finance.', 5000, 5000, 'active', 'medium', 'Sponsorships only come after reaching 1k+ constant listeners.', false),
('Newsletter (Substack/Beehiiv)', 'paid-newsletter-india', cat_content, 'Curate insights on a specific industry via weekly emails.', 'Build a direct relationship with readers. Charge for a premium tier.', 0, 5000, 'active', 'high', 'Consistency is key. 50% of the work is just getting people to sign up.', true),
('Faceless "Cash Cow" Channels', 'faceless-youtube-empire', cat_content, 'Entertainment channels using stock footage and AI voice.', 'Niche: Space, History, or Luxury. Outsource script, edit, and voice.', 20000, 25000, 'semi-passive', 'medium', 'YouTube algorithm changes can hit these hard. High competition.', true),
('Stock Analysis on Twitter/X', 'twitter-fin-analyst', cat_content, 'Charge for a private circle or newsletter on stock tips.', 'Build authority by sharing quality analysis. Monetize via X subscriptions.', 0, 10000, 'active', 'medium', 'Requires SEBI registration if giving specific advice.', false),
('Medium Partner Program', 'medium-writing-program', cat_content, 'Get paid for every minute someone spends reading your stories.', 'Write human-centric, high-quality stories on Medium. Global payouts.', 0, 2000, 'active', 'low', 'Requires Stripe-supported payout (now available in India!).', false),
('Pinterest Affiliate Hub', 'pinterest-affiliate-marketing', cat_content, 'Curate aesthetic products on Pinterest and link to Amazon/Myntra.', 'Daily pins on Home Decor, Fashion, or Tech. Passive traffic for months.', 0, 3000, 'passive', 'low', 'Requires volume (10-20 pins a day initially).', false),
('Short-form Video Editor', 'reel-video-editor', cat_content, 'Create viral Reels/Shorts for brands and influencers.', 'Master CapCut and Premiere Pro. Charge per video or bundle.', 0, 20000, 'active', 'low', 'Must stay updated on viral music and trends.', false),
('LinkedIn Newsletter Service', 'linkedin-newsletter-mgmt', cat_content, 'Manage company newsletters to engage their employee base or clients.', 'Draft and schedule bi-weekly updates on LinkedIn''s native newsletter tool.', 0, 10000, 'active', 'low', 'Requires professional B2B writing skills.', false),
('Documentation-as-a-Service', 'writer-documentation-service', cat_content, 'Help early-stage startups document their internal processes.', 'Write SOPs, internal wikis, and user manuals for growing teams.', 0, 25000, 'active', 'low', 'High demand in remote/distributed companies.', false),
('AI-Assisted Prompt Engineer', 'prompt-engineer-content', cat_content, 'Create high-end visual or text assets using AI for brands.', 'Deliver unique Midjourney art or LLM copy. Sell as a service.', 2000, 20000, 'active', 'medium', 'AI is moving fast; you need to evolve every month.', false);

-- 3. AFFILIATE MARKETING (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('Amazon Influencer Store', 'amazon-influencer-hub', cat_affiliate, 'A curated shop page on Amazon where you earn on every referral.', 'Create a storefront (e.g., "Best Work-from-home Setup") and drive traffic via YouTube/Insta.', 0, 10000, 'semi-passive', 'low', 'You need an existing social following to get approved.', true),
('Credit Card Referral (EarnKaro)', 'credit-card-affiliate', cat_affiliate, 'Earn up to ₹500-1500 for every credit card application approval.', 'Use EarnKaro to link to various banks. Focus on "best travel cards" or "fuel cards".', 0, 15000, 'active', 'low', 'Requires building trust. People don''t share financial details easily.', true),
('Hosting Affiliate (High Ticket)', 'web-hosting-referral', cat_affiliate, 'Promote Hostinger/Bluehost to new businesses.', 'One of the highest-paying niches. Earn ₹3000+ per sale.', 1000, 10000, 'active', 'high', 'Very competitive SEO niche. High churn rate.', false),
('MakeMyTrip / Travel Affiliate', 'travel-deal-hub', cat_affiliate, 'Earn commission on flights, hotels, and holiday packages.', 'Run a Telegram channel for "Flight Loot Deals" or "Budget Weekend Trips".', 0, 5000, 'semi-passive', 'medium', 'Margins are thin for solo flights; focus on hotel bundles.', false),
('VPN Affiliate Programs', 'vpn-referral-niche', cat_affiliate, 'Recurring commissions for selling NordVPN, Surfshark, etc.', 'Focus on privacy and "unblocking content" messaging.', 0, 10000, 'active', 'medium', 'Global competition. Good if targeting tech-savvy Indians.', false),
('Online Course Affiliate', 'course-affiliate-hub', cat_affiliate, 'Promote courses from Udemy, Coursera, or Indian EdTech.', 'Target students and professionals looking for upskilling.', 0, 3000, 'semi-passive', 'low', 'Udemy commissions are small; Coursera/Specialized platforms pay better.', false),
('Health & Wellness (iHerb)', 'health-supplement-affiliate', cat_affiliate, 'Earn commissions on vitamins and supplements.', 'Niche: Keto, Vegan, or Gym-goer essentials.', 0, 5000, 'active', 'medium', 'Supplements require cautious marketing to avoid legal claims.', false),
('PolicyBazaar Affiliate', 'insurance-referral-india', cat_affiliate, 'Refer people for Term insurance or Health insurance.', 'Helping people choose the right plan. Very high trust required.', 0, 20000, 'active', 'high', 'Highly regulated. Use official aggregator platforms.', false),
('B2B Software (SEMrush/Canva)', 'saas-tool-affiliate', cat_affiliate, 'Refer businesses to tools they need for daily operations.', 'Promote tools like Canva Pro or project management software.', 0, 10000, 'semi-passive', 'medium', 'Great for recurring income if the user stays subscribed.', true),
('Fashion Affiliate (Myntra/Ajio)', 'fashion-curation-affiliate', cat_affiliate, 'Curate "Looks of the week" and earn on every purchase.', 'Drive traffic using Instagram Reels or YouTube hauls.', 0, 8000, 'active', 'low', 'High return rates on clothing can reverse your commission.', false),
('Gaming Affiliate (Epic/Steam)', 'gaming-referral-empire', cat_affiliate, 'Earn when people buy games or in-game skins via your link.', 'Successful for gaming streamers and Discord community owners.', 0, 5000, 'active', 'low', 'Only works for high-volume niche audiences.', false),
('Aggregator Loot Channel', 'telegram-loot-channel', cat_affiliate, 'Mass affiliate channel posting daily price drops on everything.', 'Requires bots to track prices across Amazon, Flipkart, and more.', 0, 30000, 'active', 'high', 'Hard to grow from zero. Requires initial marketing push.', true);

-- [Remaining classifications: Digital Products, Rental Income, Online Business, Freelancing, Automation, Offline Business]
-- Due to length, I will proceed with the next batch of 12 for the remaining 6 categories.

-- 4. DIGITAL PRODUCTS (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('Excel Financial Templates', 'excel-finance-templates', cat_digital, 'Professional budget trackers and financial models.', 'Sell on Gumroad or Etsy. Focus: Indian Tax planning or SMB accounting.', 0, 10000, 'passive', 'low', 'Need to be an Excel/Sheets power user.', true),
('UI/UX Design Kits (Figma)', 'figma-ui-kits', cat_digital, 'High-quality components for designers to speed up workflow.', 'Sell on Figma Community or UI8. Niche: Indian E-commerce or Fintech.', 0, 25000, 'passive', 'medium', 'Design must be world-class to compete globally.', false),
('Stock Sound Library', 'stock-sound-effects', cat_digital, 'Unique Indian background sounds, traffic, city-life, and music.', 'Sell on AudioJungle or Pond5. High demand for authentic local sounds.', 10000, 5000, 'passive', 'low', 'Requires high-quality recording equipment.', false),
('Premium Font Creation', 'handwritten-fonts-digital', cat_digital, 'Design unique English or Indic fonts for brands.', 'Sell on MyFonts or Creative Market.', 0, 8000, 'passive', 'medium', 'Requires understanding of typography and kerning.', false),
('Print-on-Demand Designs', 'pod-design-portfolio', cat_digital, 'Design graphics for T-shirts, mugs, and posters.', 'Upload to Redbubble, TeePublic, or Printrove (India).', 0, 5000, 'passive', 'low', 'Margins are thin; requires high volume of designs.', false),
('WordPress Premium Themes', 'wordpress-theme-dev', cat_digital, 'Develop niche WP themes for specific businesses.', 'ThemeForest is the big player. Focus: Real Estate or Astrology niches.', 0, 50000, 'passive', 'high', 'Requires high technical skill and constant updates.', true),
('Chrome Browser Extensions', 'chrome-extension-micro-saas', cat_digital, 'Small tools that solve specific problems in the browser.', 'Charge a small fee or use a freemium model. Focus: Productivity.', 5000, 15000, 'passive', 'medium', 'Google Web Store policies change frequently.', false),
('Digital Art & NFTs', 'digital-art-portfolio', cat_digital, 'Create and sell character art or Concept Art.', 'Platforms: ArtStation, OpenSea. Focus on high-quality 2D/3D art.', 0, 10000, 'passive', 'high', 'NFT hype has cooled; focus on utility and quality.', false),
('Professional Resume Templates', 'resume-cv-templates', cat_digital, 'ATS-friendly resume designs in Word and Canva.', 'Sell for ₹99-₹499 on Instagram or your own site.', 0, 7000, 'passive', 'low', 'Easy to copy; focus on "Bonus items" like cover letters.', false),
('Anki Flashcards (Exams)', 'anki-flashcards-med-law', cat_digital, 'Premade memory cards for NEET, JEE, or UPSC.', 'Extremely popular among students. High viral potential.', 0, 15000, 'passive', 'low', 'Quality of content must be 100% accurate.', true),
('Midjourney Prompt Guide', 'ai-prompt-libraries', cat_digital, 'Specific "recipes" to get high-end results from AI tools.', 'Sell as a PDF or Web guide. Target: Marketing agencies.', 0, 4000, 'passive', 'low', 'Prompts get outdated fast as AI models upgrade.', false),
('Digital Wedding Invitations', 'digital-invitation-templates', cat_digital, 'Elegant, moving, or interactive invites for Indian weddings.', 'Sell as templates or a customization service.', 0, 20000, 'active', 'low', 'Peak season income (Winter/Summer) is much higher.', false);

-- 5. RENTAL INCOME (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('Commercial Subletting', 'commercial-micro-office', cat_rental, 'Lease a big hall and divide it into small 2-desk cabins.', 'Rent out to freelancers or small scale brokers. High footfall area.', 100000, 30000, 'semi-passive', 'medium', 'Requires legal permission from original owner for subleasing.', true),
('Warehouse Storage Space', 'warehouse-storage-rental', cat_rental, 'Convert a godown into safe storage for home-shifted items.', 'People often need space to keep furniture when moving cities temporarily.', 50000, 15000, 'passive', 'low', 'Security and moisture control are the biggest challenges.', false),
('Car Rental (Zoomcar Host)', 'zoomcar-host-income', cat_rental, 'List your car when not in use and earn on every booking.', 'Popular in Tier 1 and Tier 2 cities. Comprehensive insurance included.', 0, 10000, 'passive', 'medium', 'Wear and tear on the car is higher than personal use.', true),
('Camera & Drone Gear', 'photography-gear-rental', cat_rental, 'Rent out professional lenses, bodies, and drones.', 'High demand for weddings and corporate events.', 20000, 8000, 'semi-passive', 'medium', 'Requires strong item-check and security deposit systems.', false),
('Furniture Rental Service', 'local-furniture-rental', cat_rental, 'Rent basic furniture to bachelors and students.', 'Beds, tables, and cabinets. Low cost entry compared to Purlife/Rentomojo.', 30000, 6000, 'passive', 'low', 'Logistics of moving furniture is the main cost.', false),
('Luxury Bag/Fashion Rental', 'luxury-fashion-lease', cat_rental, 'High-end bags or designer wear for events and weddings.', 'Target: Middle-class aspirational demographic.', 50000, 12000, 'active', 'medium', 'Requires dry cleaning and maintenance after every use.', false),
('Rooftop Solar Leasing', 'solar-roof-hosting', cat_rental, 'Host solar panels for companies and earn for used energy.', 'Platforms like MYSUN or local Discom energy credit.', 20000, 2000, 'passive', 'low', 'Net metering rules vary significantly by state.', false),
('Space for Cell Towers', 'telecom-tower-lease', cat_rental, 'Lease your roof to Jio, Airtel, or BSNL for tower placement.', 'Stable 10-20 year income stream.', 0, 15000, 'passive', 'low', 'Requires structural stability certificate and local permissions.', true),
('Billboard / Wall Ads', 'outdoor-ad-rental', cat_rental, 'Rent your highway-facing wall or roof for hoardings.', 'Charge different rates for static vs LED (Digital) hoardings.', 5000, 10000, 'passive', 'low', 'Location is EVERYTHING. Check local municipal ad taxes.', false),
('Airbnb Vacation Homestay', 'airbnb-homestay-mgmt', cat_rental, 'Convert your empty apartment into a short-stay rental.', 'Focus on unique decor and local experiences.', 50000, 40000, 'semi-passive', 'medium', 'Requires constant coordination with guests and cleaning staff.', true),
('Private Parking Lease', 'parking-space-rental', cat_rental, 'Rent out your city-center parking spot during office hours.', 'Use apps or local word-of-mouth in high-traffic areas.', 0, 3000, 'passive', 'low', 'Very low effort, good for apartment owners in CBDs.', false),
('Tools & Equipment Rental', 'power-tool-rental', cat_rental, 'Rent out drills, ladders, and saws to DIY enthusiasts.', 'Neighborhood-focused small business.', 10000, 4000, 'passive', 'low', 'Items can get damaged or lost easily.', false);

-- 6. ONLINE BUSINESS (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('Dropshipping (Shopify India)', 'dropshipping-india-model', cat_online, 'Sell products without holding inventory. Ship directly to customers.', 'Master Facebook/Instagram ads. Find "winning" products on Roposo/Shiprocket.', 20000, 50000, 'active', 'high', 'High return ratios (RTO) in India can wipe out profits.', true),
('Niche Subscription Box', 'subscription-box-service', cat_online, 'Curated monthly boxes for tea lovers, dog owners, or bibliophiles.', 'Recurring monthly revenue from a loyal subscriber base.', 15000, 25000, 'active', 'medium', 'Logistics and sourcing variety every month is a challenge.', false),
('White-label Supplement Brand', 'white-label-wellness', cat_online, 'Create your own brand of proteins or vitamins using contract manufacturing.', 'Focus on your own niche marketing and label design.', 100000, 100000, 'active', 'high', 'Strict FSSAI regulations and high marketing costs.', true),
('Managed Website Hosting', 'managed-wordpress-hosting', cat_online, 'Resell hosting but manage it for local non-tech businesses.', 'Charge for hosting + maintenance + small monthly edits.', 1000, 15000, 'semi-passive', 'medium', 'Requires some tech knowledge to handle server downtime.', false),
('Micro-SaaS Product', 'micro-saas-apps', cat_online, 'Small software that solves one specific task (e.g. GST calculator for Shopify).', 'Recurring monthly fees for a lightweight tool.', 5000, 30000, 'passive', 'medium', 'Low competition but requires coding or no-code mastery.', true),
('Niche Job Board', 'niche-job-board-biz', cat_online, 'A job board specifically for one industry (e.g. Remote Sales in India).', 'Charge companies to "feature" their jobs and recruiters to access talent.', 5000, 20000, 'semi-passive', 'low', 'Growth depends on SEO and LinkedIn positioning.', false),
('Premium Directory', 'paid-directory-service', cat_online, 'List of the "Best IVF Clinics" or "Best CA Firms" in a city.', 'Monetize via lead generation and featured listings.', 5000, 15000, 'passive', 'low', 'Need high-quality SEO to rank for local keywords.', false),
('Domain Flipping', 'domain-flipping-india', cat_online, 'Buy "brandable" dot-in domains and sell them to new startups.', 'Auction on GoDaddy or Dan.com.', 1000, 5000, 'passive', 'high', 'Many domains are worthless; only 1% will ever sell.', false),
('Website Flipping', 'blog-flipping-service', cat_online, 'Buy an under-performing blog, fix the SEO/content, and sell for 10x.', 'Like real estate house-flipping, but for digital assets.', 10000, 50000, 'active', 'high', 'Requires high SEO and Monetization expertise.', true),
('Remote Tutoring Agency', 'online-tutoring-platform', cat_online, 'Match qualified teachers with international students.', 'High margins if paying teachers in INR and charging in USD/EUR.', 5000, 40000, 'active', 'medium', 'Managing a quality teacher roster is the hardest part.', false),
('AI Greeting Card Service', 'ai-greeting-biz', cat_online, 'Sell custom poetic or artistic cards generated by AI.', 'Unique, personalized physical cards sent via courier.', 2000, 10000, 'active', 'low', 'Fun side business, requires good automated shipping partners.', false),
('Digital Newsletter Management', 'newsletter-growth-agency', cat_online, 'Help brands manage their Beehiiv/Substack growth.', 'Run lead magnets and ad campaigns for newsletter owners.', 0, 30000, 'active', 'low', 'Very new niche with high demand.', false);

-- 7. FREELANCING (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('Video Editor (YouTube/Ads)', 'video-editor-pro', cat_freelance, 'Professional editing for creators and businesses.', 'Edit 15-min videos or high-impact 30-sec social ads.', 10000, 40000, 'active', 'low', 'Requires a system with good specs to edit high-res footage.', true),
('Technical Content Writer', 'technical-content-writing', cat_freelance, 'Write blog posts for SaaS, AI, and Fintech companies.', 'Deliver high-quality SEO content. Charge per word or project.', 0, 30000, 'active', 'low', 'AI tools are making basic content cheap; you must be an expert.', true),
('Executive Virtual Assistant', 'executive-va-service', cat_freelance, 'Remote right-hand for busy international executives.', 'Email, scheduling, and project management tasks.', 0, 25000, 'active', 'low', 'Requires perfect English and high organizational skills.', false),
('Full-Stack App Developer', 'app-dev-freelance', cat_freelance, 'Build custom Web/Mobile apps for clients.', 'Master React, Node, or Flutter. High global demand.', 0, 80000, 'active', 'medium', 'Constant learning required as tech changes daily.', true),
('Digital Marketing Consultant', 'marketing-consultancy-freelance', cat_freelance, 'Advise SMEs on Meta Ads, Google Ads, and Funnels.', 'Focus on "Performance Marketing" (Result-driven).', 1000, 30000, 'active', 'medium', 'Must show ROAS (Return on Ad Spend) to keep clients.', false),
('Remote Tax/GST Consultant', 'remote-gst-expert', cat_freelance, 'Handle GST filings and accounting for small startups.', 'High recurring monthly client value.', 0, 20000, 'active', 'low', 'Requires CA/CS background or specialized certification.', false),
('Legal Document Reviewer', 'legal-review-freelance', cat_freelance, 'Review contracts, NDAs, and TOS for startups.', 'Sell on platforms like Upwork or Fiverr.', 0, 40000, 'active', 'low', 'Requires Law degree and high attention to detail.', false),
('Shopify Store Setup Expert', 'shopify-expert-setup', cat_freelance, 'Help local businesses move their shop online.', 'Setup theme, products, payments, and shipping apps.', 0, 20000, 'active', 'low', 'Good "entry" freelance service with high local demand.', true),
('Proofreading & Editing', 'proofreader-editor-pro', cat_freelance, 'Polishing e-books, articles, and whitepapers.', 'Focus on niche academic or professional editing.', 0, 10000, 'active', 'low', 'Pay is lower per hour, but consistent flow of work.', false),
('Remote Data Entry Expert', 'data-entry-specialist', cat_freelance, 'High-volume data cleaning and spreadsheet management.', 'Usually for US/UK research firms.', 0, 8000, 'active', 'low', 'Very repetitive. Pay is low unless doing "Complex" data work.', false),
('Social Media Manager', 'social-media-manager-freelance', cat_freelance, 'Content calendar, posting, and engagement for brands.', 'Requires graphic design (Canva) and copy skills.', 0, 25000, 'active', 'low', 'Often leads to full-time agency model.', false),
('Brand Identity Designer', 'brand-designer-freelance', cat_freelance, 'Logo, colors, and typography for new startups.', 'Deliver full brand kits. Charge ₹10k-50k per kit.', 0, 30000, 'active', 'low', 'Portfolio is everything.', false);

-- 8. AUTOMATION (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('No-Code Workflow Setup (Zapier)', 'zapier-workflow-expert', cat_automation, 'Automate tasks between 5000+ apps.', 'Example: Auto-saving email attachments to Google Drive + Team Alert.', 1000, 20000, 'active', 'low', 'Requires logical thinking and knowledge of API limits.', true),
('B2B Chatbot Deployment', 'chatbot-agency-services', cat_automation, 'Deploy custom AI chatbots on WhatsApp and Websites.', 'Help businesses answer FAQs and capture leads 24/7.', 5000, 30000, 'active', 'medium', 'Client expectations on AI "intelligence" can be unrealistic.', true),
('Automated Trading Bots', 'algo-trading-bots', cat_automation, 'Set up systems to trade stocks based on preset logic.', 'Use Python or Amibroker. Truly passive once profitable.', 50000, 5000, 'passive', 'high', 'Can lose principal quickly in volatile markets.', false),
('Email Drip Automation', 'email-automation-marketing', cat_automation, 'Automated email sequences to convert leads into customers.', 'Master tools like ConvertKit or Mailchimp.', 0, 15000, 'active', 'low', 'Requires high-quality copywriting skills.', false),
('Web Scraping-as-a-Service', 'web-scraping-provider', cat_automation, 'Provide clean data extracts for research or competitor monitoring.', 'Example: Track Amazon prices daily for a client.', 2000, 20000, 'passive', 'medium', 'Anti-scraping tech on major sites is a constant battle.', false),
('Auto Social Scheduling', 'social-automation-mgmt', cat_automation, 'Setup Buffer/Hootsuite for a brand to run on autopilot for months.', 'Batch content creation once, automate the rest.', 0, 10000, 'semi-passive', 'low', 'Engagement (replying to comments) still needs humans.', false),
('Lead Gen Automation', 'automated-lead-gen', cat_automation, 'Search LinkedIn/Web for leads and auto-verify emails.', 'Charge per qualified lead delivered to the client.', 5000, 40000, 'passive', 'medium', 'Spam filters are getting smarter; must be very targeted.', true),
('Automated Invoicing Systems', 'custom-billing-automation', cat_automation, 'Help freelancers/SMEs automate their collection process.', 'Setup recurring billing and auto-reminders.', 0, 5000, 'active', 'low', 'One-time setup fee + small maintenance.', false),
('Smart Home Tech Consultant', 'smart-home-integration', cat_automation, 'Automate local homes with IoT devices (Lights, Locks, AC).', 'Design the "Logic" for someone''s smart home.', 5000, 25000, 'active', 'medium', 'Requires physical site visits initially.', false),
('RPA for SMBs', 'rpa-automation-expert', cat_automation, 'Automate boring office spreadsheet work via UI Path/Power Automate.', 'Software bots that do what humans click and type.', 0, 50000, 'active', 'medium', 'High technical mastery required.', true),
('API Connector Service', 'api-integration-agency', cat_automation, 'Build custom bridges between two softwares for a client.', 'One-time custom coding projects.', 0, 30000, 'active', 'medium', 'Requires Node.js or Python expertise.', false),
('Auto-Content Syndication', 'content-syndication-automation', cat_automation, 'Auto-reposting your blog to Medium, LinkedIn, and Twitter.', 'Setup "Master" workflows for content dissemination.', 1000, 5000, 'passive', 'low', 'Can look "spammy" if not curated correctly.', false);

-- 9. OFFLINE BUSINESS (12 Ideas)
INSERT INTO income_ideas (title, slug, category_id, short_description, full_description, initial_investment_min, monthly_income_min, effort_level, risk_level, reality_check, is_featured) VALUES
('Self-Service Laundry', 'laundromat-india-local', cat_offline, 'Pay-per-wash machines in student/bachelor hubs.', 'Laundromats are still new in India; high potential in IT cities.', 500000, 40000, 'semi-passive', 'medium', 'High initial capital and maintenance costs.', true),
('Organic Terrace Farming', 'managed-terrace-farming', cat_offline, 'Set up and manage organic gardens on people''s rooftops.', 'Monthly subscription for maintenance + seedlings.', 10000, 15000, 'active', 'low', 'Requires high knowledge of seasonal Indian plants.', false),
('Managed Cloud Kitchen', 'cloud-kitchen-sublet', cat_offline, 'Rent out a kitchen space to online-only food startups.', 'You provide the infra (gas, sinks, licenses), they provide the food.', 300000, 50000, 'passive', 'medium', 'Licenses (FSSAI/Fire) are your responsibility.', true),
('Micro Co-working Space', 'apartment-coworking-space', cat_offline, 'Convert your extra apartment into a 5-desk quiet work zone.', 'High-speed internet, power backup, and unlimited tea.', 50000, 25000, 'passive', 'low', 'Security of the residential building is a concern.', false),
('Private Tuition / Exam Center', 'local-tuition-hub', cat_offline, 'Niche center for specific competitive exams (CA/UPSC/NEET).', 'Rent out a hall and hire freelance teachers.', 100000, 40000, 'active', 'medium', 'Reputation of results is the only thing that drives growth.', false),
('Niche Event Management', 'pet-birthday-planner', cat_offline, 'Specialized events like "Pet Birthdays" or "Baby Showers".', 'High margins in emotional/luxury niche events.', 5000, 20000, 'active', 'low', 'Highly seasonal and depends on local word-of-mouth.', false),
('Deep Cleaning Services', 'home-deep-cleaning', cat_offline, 'Post-renovation or pre-wedding full house sanitization.', 'Hire trained labor and provide industrial gear.', 30000, 30000, 'active', 'medium', 'Scaling labormanagement is the biggest hurdle.', true),
('Mobile On-demand Car Wash', 'waterless-car-wash', cat_offline, 'Eco-friendly waterless car cleaning at customer''s doorstep.', 'Subscription based monthly model.', 5000, 15000, 'active', 'low', 'Low entry barrier; high local competition.', false),
('Exotic Plant Nursery', 'rare-plant-shop', cat_offline, 'Propagate and sell hard-to-find indoor plants.', 'Sell on Instagram and locally.', 20000, 10000, 'semi-passive', 'low', 'Plants can die easily due to weather; needs care.', false),
('Pet Daycare / Boarding', 'pet-boarding-home', cat_offline, 'Watch over pets while owners travel.', 'Home-based, high-trust boarding.', 5000, 15000, 'active', 'low', 'Must love animals and have space for them to play.', false),
('Solar Maintenance Unit', 'solar-panel-cleaning', cat_offline, 'Specialized cleaning for industrial/residential solar panels.', 'Panels lose 20% efficiency if dusty. Recurring maintenance service.', 10000, 25000, 'active', 'low', 'Requires safety gear for rooftop work.', true),
('Local Logistics Point', 'pickup-drop-center', cat_offline, 'Host a pickup point for Amazon/Flipkart/Ecom Express.', 'Small shop owners earn per parcel handled.', 0, 5000, 'passive', 'low', 'Requires a permanent shop location and high reliability.', false);

END $$;
